version: 0.2

phases:
  install:
    runtime-versions:
    # this will install the java and maven dependency software's
      java: corretto11  
  pre_build:
    commands:
     # - echo code scanning using sonar cube 
     # - mvn verify sonar:sonar
       - echo connecting to code aws aritifacrt 
       - FOR /F "tokens=*" %g IN ('aws codeartifact get-authorization-token --domain cbca --domain-owner 092355029172 --region us-east-1 --query authorizationToken --output text') do (SET CODEARTIFACT_AUTH_TOKEN=%g)
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -lrta
      - ls -lrt $CODEBUILD_SRC_DIR/settings.xml
      - cp -pvr $CODEBUILD_SRC_DIR/settings.xml ~/.m2/settings.xml
      - mvn deploy 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/b78am.war
