version: 0.2

phases:
  install:
    runtime-versions:
    # this will install the java and maven dependency software's
      java: corretto11  
  pre_build:
    commands:
      - echo code scanning using sonar cube 
      #-mvn verify sonar:sonar
      -mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mahi-b78am_new-proj
  build:
    commands:
      - echo Build started on `date`
      - mvn install 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/b78am.war
